export const CONTACT_EMAIL_MAX_LENGTH = 254
export const CONTACT_SUBJECT_MIN_LENGTH = 3
export const CONTACT_SUBJECT_MAX_LENGTH = 160
export const CONTACT_MESSAGE_MIN_LENGTH = 10
export const CONTACT_MESSAGE_MAX_LENGTH = 4000
